### ISSUE TITLE
Error while installing package with node 14

### ISSUE THREAD

**Issue by jerryjoseph-net** [noamokman/impersonator#1]
I get the following errors while installing the package.

C:\Code\Git\e2e-test>npm install --save impersonator

> impersonator@0.0.1 install C:\Code\Git\e2e-test\node_modules\impersonator
> node-gyp rebuild

C:\Code\Git\e2e-test\node_modules\impersonator>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  impersonator.cpp
  Impersonation.cpp
  win_delay_load_hook.cc
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(15): error C2660:
'v8::Value::ToString': function does not take 0 arguments [C:\Code\Git\e2e-test\node_m
odules\impersonator\build\impersonator.vcxproj]**
  c:\users\b924jo\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(2810): note: see declaration of 'v8::Value::To
  String' (compiling source file ..\src\impersonator.cpp)
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(15): error C2512:
'v8::String::Utf8Value::Utf8Value': no appropriate default constructor available [C:\Code\Git\
e2e-test\node_modules\impersonator\build\impersonator.vcxproj]
c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(24): error C2664:
'void v8::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'bool' [C:\
Code\Git\e2e-test\node_modules\impersonator\build\impersonator.vcxproj]**
          with
          [
              T=v8::Value
          ]
  c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(24): note: No us
  er-defined-conversion operator available that can perform this conversion, or the operator cannot be called
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(29): error C2664:
'void v8::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'bool' [C:\
Code\Git\e2e-test\node_modules\impersonator\build\impersonator.vcxproj]**
          with
          [
              T=v8::Value
          ]
  c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(29): note: No us
  er-defined-conversion operator available that can perform this conversion, or the operator cannot be called
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(34): error C2664:
'void v8::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'bool' [C:\
Code\Git\e2e-test\node_modules\impersonator\build\impersonator.vcxproj]**
          with
          [
              T=v8::Value
          ]
  c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(34): note: No us
  er-defined-conversion operator available that can perform this conversion, or the operator cannot be called
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(41): error C2664:
'void v8::ReturnValue<T>::Set(uint32_t)': cannot convert argument 1 from 'v8::MaybeLocal<v8::String>' to 'bool' [C:\
Code\Git\e2e-test\node_modules\impersonator\build\impersonator.vcxproj]**
          with
          [
              T=v8::Value
          ]
  c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(41): note: No us
  er-defined-conversion operator available that can perform this conversion, or the operator cannot be called
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(44): error C2065:
'Handle': undeclared identifier [C:\Code\Git\e2e-test\node_modules\impersonator\build\
impersonator.vcxproj]
c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(44): error C2275:
'v8::Object': illegal use of this type as an expression [C:\Code\Git\e2e-test\node_mod
ules\impersonator\build\impersonator.vcxproj]**
  c:\users\b924jo\appdata\local\node-gyp\cache\14.17.6\include\node\v8.h(3664): note: see declaration of 'v8::Object'
**c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(44): error C2065:
'exports': undeclared identifier [C:\Code\Git\e2e-test\node_modules\impersonator\build
\impersonator.vcxproj]
c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(44): error C2182:
'init': illegal use of type 'void' [C:\Code\Git\e2e-test\node_modules\impersonator\bui
ld\impersonator.vcxproj]
c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(44): error C2448:
'init': function-style initializer appears to be a function definition [C:\Code\Git\e2
e-test\node_modules\impersonator\build\impersonator.vcxproj]
c:\code\git\e2e-test\node_modules\impersonator\src\impersonator.cpp(49): warning C4312
: 'type cast': conversion from 'int' to 'node::addon_register_func' of greater size [C:\Code\Git\
e2e-test\node_modules\impersonator\build\impersonator.vcxproj]**
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Code\Git\e2e-test\node_modules\impersonator
gyp ERR! node -v v14.17.6
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN @fimbul/bifrost@0.21.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-config-airbnb@5.11.2 requires a peer of tslint@^5.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-consistent-codestyle@1.16.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-eslint-rules@5.4.0 requires a peer of typescript@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of tslint@^5.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.2.1 requires a peer of typescript@^2.1.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN e2e-test@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! impersonator@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by noamokman** [comment]
wow this is a very old repo from 7 years ago,
node 14 wasn't available then.
Feel free to take the code and do with it whatever you want, but I'm not sure if this is working
